### ISSUE TITLE
Can't open on Mac OS

### ISSUE THREAD

**Issue by viniciusatique** [cxhawk/liveSubs#1]
Hello. I can't install it on Mac OS Big Sur. It tells me I don't have permission. If I bypass it through Terminal, it tries to open and tells me it is corrupted. If I bypass again, it crashes.

Any thoughts?

**Comment by cxhawk** [comment]
Can you post a screenshot? The app should be notarized already but you can try right click on it and then select open to bypass the check. Make sure you download from the releases prebuilt binary.

**Comment by cxhawk** [comment]
Try again with v1.2.3

**Comment by viniciusatique** [comment]
> Try again with v1.2.3

Now it works perfectly. Cheers!
