### ISSUE TITLE
Lower Thirds Edit window confirm/cancel not working as expected

### ISSUE THREAD

**Issue by yttuo** [cxhawk/liveSubs#6]
To reproduce: After importing an item in Lower Thirds, click on edit icon to open "Edit" window to add/remove/update description. "Cancel" and "Confirm" buttons seem to be working in the same way and both save the latest contents on the screen. Plus I expect "Confirm" can also close the window but only "Cancel" does. Also the "x" sign on the up right corner doesn't work.

**Comment by cxhawk** [comment]
fixed in 1.3.7
